{{- if .Values.deployClusterServiceBroker }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: {{ template "servicebroker.fullname" . }}
spec:
  url: http://{{ template "servicebroker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
