kind: Service
apiVersion: v1
metadata:
  name: {{ template "servicebroker.fullname" . }}
  labels:
    app: {{ template "servicebroker.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "servicebroker.fullname" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
